install: ;@echo "Installing -Ecoleta- mobile..."; \
		npm install;

run: ;@echo "Running -Ecoleta- mobile..."; \
	npm start; \
	expo install expo-font @expo-google-fonts/ubuntu @expo-google-fonts/roboto;
